apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adro.fullname" . }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.size | default .Values.artifact.size }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
